//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleEFLINQToEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int IdCalificacion { get; set; }
        public int IdMatricula { get; set; }
        public int IdDesempeno { get; set; }
        public double Nota { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Desempeno Desempeno { get; set; }
        public virtual Matricula Matricula { get; set; }
    }
}
